title = "本地环境"

[admin]
Name = "admin"
ListenPort = 8012
debug = true
LogLevel = "debug"

[database]
username = 'carver'
password  = 'carver'
database = 'carver'
addr = "127.0.0.1"
ports = [ 8001, 8001, 8002 ]
connection_max = 5000
enabled = true
system_port = 8012



[redis]
Addr = "127.0.0.1:6379"
Auth = ""
DialTimeout = "1s"
ReadTimeout = "200ms"
WriteTimeout = "200ms"

[servers]

  [servers.local]
  db = "carver1"
  pwd = "carver1"

  [servers.test]
  db = "carver2"
  pwd = "carver2"

[other]
data = [ ["local", "test"], [1, 2] ]
type = ["git","github"]


