//测试环境配置
title = "【测试环境】"
[api]
	ListenPort = 8012
	Debug = true
	LogLevel = "debug"
 
[admin]
	ListenPort = 8888
	Debug = true
	LogLevel = "debug"
 
[database.main]
	DSN = "root:amdin123@tcp(127.0.0.1:3306)/weifou?charset=utf8"
	ReadDSN =  []
	Active = 10
	Idle = 10
	IdleTimeout = "300s"
	QueryTimeout = "1s"
	ExecTimeout = "1s"
	TranTimeout = "1s"
 
 
[redis.main]
	Addr = "127.0.0.1:6379"
	Auth = ""
	DialTimeout = "1s"
	ReadTimeout = "200ms"
	WriteTimeout = "200ms"

